name: CI

on:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: Goreleaser CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --snapshot --skip-publish --clean --skip-sign
      - name: Tar files
        run: tar -czvf artifacts.tar.gz dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar.gz
